# Generated by Django 4.2.6 on 2023-11-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EuroTravel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("tour_cost", models.IntegerField()),
                ("tour_description", models.TextField()),
                ("hotel", models.CharField(max_length=100)),
                ("hotel_description", models.TextField()),
                ("transit", models.CharField(max_length=100)),
                ("food", models.CharField(max_length=200)),
                ("excursions", models.CharField(max_length=200)),
            ],
        ),
    ]
